 # This is a basic workflow to help you get started with Actions

name: SPASE Manual Validation

# Controls when the action will run. 
# Triggers the workflow manually
on: workflow_dispatch
# Triggers the workflow on push
# on: push
#  push:
#    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate"
  validate:
    name: Validation and referential check
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install spase-resource-tools
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Install SPASE-Resource-tools
        run: npm install -g spase-resource-tools

       # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Prepare for logs
      - name: Prepare Log directory
        run: mkdir -p logs

      # Check descriptions for schema conformance
      - name: Schema compliance ...
        run: spase-validate -r . > logs/validate.log

      # Perform 
      - name: Referential checks ...
        run: spase-refcheck -r . >> logs/validate.log

      # Upload logs
      - name: Upload log artifacts
        uses: actions/upload-artifact@v2
        with:
          name: validate-log
          path: logs/validate.log

      # Check if log contains any INVALID items
      - name: Check for invalid items
        run: |
          if [ -f logs/validate.log ]; then
            set +e
            echo -n "Number of invalid files: "
            # Turn off exit code - we handle it differently
            grep -c "^ INVALID:" logs/validate.log
            if [ `grep -c "^ INVALID:" logs/validate.log` -eq 0 ]; then
              echo "No FAILURE found: $?"
              exit 0
            else
              echo "FAILURE found: $?"
              exit 1
            fi
            set -e
          fi
